site_name: PyTorch Course
site_description: The best online and free PyTorch tutorial
site_url: https://ksopyla.github.io/pytorch-course/

theme:
  name: material
  features:
    - navigation.tabs # If you want tabs for top-level sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
    - 'PyTorch Course Structure': pytorch-course-sturcture.md
    - 'Windows Environment Installation': 00-getting-started/windows-pytorch-installation.md
    - 'Linux Environment Installation': 00-getting-started/linux-pytorch-installation.md
    - 'MacOS Environment Installation': 00-getting-started/macos-pytorch-installation.md
    - 'Hello PyTorch': 00-getting-started/01_hello_pytorch.ipynb
  - Tensors:
    - 'Tensors': 01-tensors/01_tensors_intro.ipynb

plugins:
  - search
  - mkdocs-jupyter

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences # For better code blocks
  - admonition # For notes, warnings, etc. 