site_name: PyTorch Course
site_description: The best online and free PyTorch tutorial
site_url: https://pytorchcourse.com/
repo_url: https://github.com/ksopyla/pytorch-course

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs 
    - navigation.tabs.sticky     
    - navigation.top
    - navigation.sections        
    - navigation.expand          
    - navigation.path            
    - navigation.footer        
    - search.highlight
    - search.suggest
    - announce.dismiss
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow
  palette:
    # Light mode - "Laboratory Clean"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple      # More "mad scientist" feel
      accent: amber            # Electric/lightning accent
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    
    # Dark mode - "Midnight Laboratory" 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  icon:
    logo: material/flask-outline  # Mad scientist flask icon
    repo: fontawesome/brands/github

nav:
  - Getting Started:
    - 'PyTorch Course Structure': pytorch-course-structure.md
    - 'Windows Environment Installation': 00-getting-started/windows-pytorch-installation.md
    - 'Linux Environment Installation': 00-getting-started/linux-pytorch-installation.md
    - 'MacOS Environment Installation': 00-getting-started/macos-pytorch-installation.md
    - 'Google Colab Setup': 00-getting-started/google-colab-setup.md
    - 'Hello PyTorch': 00-getting-started/01_hello_pytorch.ipynb
  - Tensors:
    - 'Module 1': 01-tensors/00_module_1_introduction.md
    - 'Introduction to Tensors': 01-tensors/01_introduction_to_tensors.ipynb
    - 'Tensor Manipulation': 01-tensors/02_tensor_manipulation.ipynb
    - 'Data Types and Devices': 01-tensors/03_data_types_and_devices.ipynb
    - 'Tensor Math Operations': 01-tensors/04_tensor_math_operations.ipynb
    - 'Matrix Multiplication': 01-tensors/05_matrix_multiplication.ipynb
    - 'Broadcasting': 01-tensors/06_broadcasting.ipynb
    - 'Einstein Summation': 01-tensors/07_einstein_summation.ipynb
    - 'Advanced Einstein Summation': 01-tensors/08_advanced_einstein_summation.ipynb
    - 'Autograd': 01-tensors/09_autograd.ipynb
    - 'Gradient Accumulation': 01-tensors/10_gradient_accumulation.ipynb
  - NN building blocks:
    - 'Module 2': 02-torch-nn/00_module_2_introduction.md
    - 'PyTorch nn.Module': 02-torch-nn/01_nn_module.ipynb
    - 'Compose Modules': 02-torch-nn/02_compose_modules.ipynb
    - 'Saving Weights': 02-torch-nn/03_saving_weights.ipynb
    - 'Linear Layer': 02-torch-nn/04_linear_layer.ipynb
    - 'Activations': 02-torch-nn/05_activations.ipynb
    - 'Dropout': 02-torch-nn/06_dropout.ipynb
    - 'Embedding Layers': 02-torch-nn/07_embedding_layers.ipynb
    - 'Positional Encoding': 02-torch-nn/08_positional_encoding.ipynb
    - 'Normalization Layers': 02-torch-nn/09_normalization_layers.ipynb
    - 'RMS Norm': 02-torch-nn/10_rms_norm.ipynb
    - 'Training Evaluation Mode': 02-torch-nn/11_training_evaluation_mode.ipynb
    - 'Loss Functions': 02-torch-nn/12_loss_functions.ipynb
    - 'Prepare Inputs Targets': 02-torch-nn/13_prepare_inputs_targets.ipynb
    - 'Interpreting Reduction Modes': 02-torch-nn/14_interpreting_reduction_modes.ipynb
  # # Training Workflows section - covers core training concepts and practices
  # - Training Workflows:
  #   - 'Training Loop': 03-training-nn/01_training_loop.ipynb
  #   - 'Optimizers Schedulers': 03-training-nn/02_optimizers_schedulers.ipynb
  #   - 'Datasets DataLoaders': 03-training-nn/03_datasets_dataloaders.ipynb
  #   - 'GPU Acceleration': 03-training-nn/04_gpu_acceleration.ipynb
  #   - 'Training Optimization': 03-training-nn/05_training_optimization.ipynb
  # # Transformers section - covers transformer architecture and components
  # - Transformers:
  #   - 'Positional Embeddings': 04-transformers/01_positional_embeddings.ipynb
  #   - 'Attention Mechanism': 04-transformers/02_attention_mechanism.ipynb
  #   - 'Multi-Head Attention': 04-transformers/03_multi_head_attention.ipynb
  #   - 'Other Attention Implementations': 04-transformers/04_other_attention_implementations.ipynb
  #   - 'Transformer Encoder': 04-transformers/05_transformer_encoder.ipynb
  # # Advanced PyTorch section - covers advanced concepts and optimization techniques
  # - Advanced PyTorch:
  #   - 'Hooks': 05-advanced-pytorch/01_hooks.ipynb
  #   - 'Distributed Training Concepts': 05-advanced-pytorch/02_distributed_training_concepts.ipynb
  #   - 'Model Optimization Concepts': 05-advanced-pytorch/03_model_optimization_concepts.ipynb
  #   - 'Torchscript JIT': 05-advanced-pytorch/04_torchscript_jit.ipynb
  #   - 'Profiling': 05-advanced-pytorch/05_profiling.ipynb
  # # HuggingFace Transformers section - covers practical applications using HuggingFace
  # - HuggingFace Transformers:
  #   - 'HuggingFace Transformers': 06-huggingface-transformers/01_huggingface_transformers.ipynb
  #   - 'Fine Tuning Transformers': 06-huggingface-transformers/02_fine_tuning_transformers.ipynb

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags                      # Enable content tagging - removed deprecated tags_file setting
  - mkdocs-jupyter:
      execute: false          # Don't execute notebooks during build
      include_source: true    # Include source code
  - git-revision-date-localized:
      type: date
      enable_creation_date: true

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra:
  generator: false  # Remove "Made with Material for MkDocs"
  
  # Single announcement (not a list)
  announcement:
    title: "🎉 New Module Available!"
    content: "Check out our latest Transformers section with hands-on exercises"
  
  # Social media links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ksopyla/pytorch-course
      name: Join Professor Torchenstein's Laboratory on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ksopyla
      name: Follow the Professor's Latest Experiments
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/krzysztof-sopyla/
      name: Connect with Professor Torchenstein on LinkedIn
    - icon: material/email
      link: mailto:krzysztofsopyla@gmail.com
      name: Send a Message to the Laboratory
  
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this lesson helpful, my dear minion?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This lesson was electrifying!
          data: 1
          note: >
            Excellent! Professor Torchenstein is pleased with your progress.
            Consider starring the repository!
        - icon: material/emoticon-sad-outline
          name: This could use more lightning
          data: 0
          note: >
            The Professor is disappointed but not defeated! 
            Please share what confused you in the GitHub discussions.
  
  annotate:
    json: [.s2]                # Enable fun annotations
  
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/torchenstein.css    # Custom CSS for character elements

copyright: |
  Copyright &copy; 2025 Krzysztof Sopyła –
  <a href="https://github.com/ksopyla/pytorch-course/blob/main/LICENSE">MIT License</a> 