site_name: PyTorch Course
site_description: The best online and free PyTorch tutorial

theme:
  name: material
  features:
    - navigation.tabs # If you want tabs for top-level sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Lessons:
    - 'Hello PyTorch': lessons/01_hello_pytorch.ipynb

plugins:
  - search
  - mkdocs-jupyter

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences # For better code blocks
  - admonition # For notes, warnings, etc. 