name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache and install system dependencies for social cards
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
          version: 1.0

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-

      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Optimize images for web
        run: |
          python tools/optimize_images.py --quality 75 --max-width 1200 --max-height 630 --overwrite
      - name: Build MkDocs site
        env:
          JUPYTER_PLATFORM_DIRS: 1  # Suppress Jupyter deprecation warnings
        run: |
          mkdocs build --strict --verbose
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: pytorchcourse.com